source 'https://rubygems.org'

gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'erubi'
gem 'redis'
gem 'oj'

gem 'rack-mini-profiler'
gem 'rack-lineprof', git: 'https://github.com/kainosnoema/rack-lineprof'
gem 'pry-byebug'
gem 'pry-doc'
