version: '3'
services:
  web:
    container_name: 'isucon8q_web'
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: "bundle exec rackup -p 8000 -o 0.0.0.0"
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    environment:
      DB_HOST: db
      DB_USER: root
      DB_DATABASE: torb
      REDIS_HOST: redis
  nginx:
    image: saboyutaka/ngx-mruby:2.1.2
    ports:
      - 80:80
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./static:/var/www/public
      - ./config/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
      - ./logs/mysql:/var/log/mysql
      - ./db:/var/tmp
  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
  alp:
    image: saboyutaka/alp
    volumes:
      - ./logs/nginx:/logs
  myprofiler:
    image: saboyutaka/myprofiler
    command: ["-host=db", "-user=root"]
    depends_on:
      - db
  goose:
    build:
      context: docker/goose
    volumes:
      - .:/go/src/github.com/saboyutaka/isucon8q
    environment:
      DATABASE_URL: tcp:db:3306*isucon/root/
    depends_on:
      - db
volumes:
  mysql-volume:
  bundle-volume:
